"""Changed server_id to server_address

Revision ID: 0645f4eb570a
Revises: 1e7f365da6f5
Create Date: 2024-03-18 16:29:53.771500

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = '0645f4eb570a'
down_revision = '1e7f365da6f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic
    op.add_column(
        'aiagent',
        sa.Column(
            'server_address',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True
        )
    )

    # Update existing rows to set a default value for `server_address`
    op.execute(
        "UPDATE aiagent SET server_address = 'https://hogwarts.xleap.org/' "
        "WHERE server_address IS NULL"
    )

    # Set the `server_address` column to non-nullable
    op.alter_column('aiagent', 'server_address', nullable=False)

    # Drop the `server_id` column
    op.drop_column('aiagent', 'server_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic
    op.add_column('aiagent',
                  sa.Column('server_id',
                            sa.VARCHAR(),
                            autoincrement=False,
                            nullable=False))
    op.drop_column('aiagent', 'server_address')
    # ### end Alembic commands ###
