"""added boolean column to indicate if agent is active

Revision ID: 1e7f365da6f5
Revises: 50b9be4775e5
Create Date: 2024-03-17 15:04:05.526543

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1e7f365da6f5'
down_revision = '50b9be4775e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column with the NOT NULL constraint
    op.add_column(
        'aiagent',
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
            server_default='False'
        )
    )
    # Update existing rows to set a default value for `is_active`
    op.execute(
        "UPDATE aiagent SET is_active = FALSE WHERE is_active IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aiagent', 'is_active')
    # ### end Alembic commands ###
