"""Updated primary key of agent to uuid

Revision ID: 50b9be4775e5
Revises: e2412789c190
Create Date: 2024-03-16 13:38:52.124303

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '50b9be4775e5'
down_revision = 'e2412789c190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('aiagent', 'id',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.GUID(),
               existing_nullable=False)
    op.create_index(op.f('ix_aiagent_id'), 'aiagent', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aiagent_id'), table_name='aiagent')
    op.alter_column('aiagent', 'id',
               existing_type=sqlmodel.sql.sqltypes.GUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
